/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef pyload_CONSTANTS_H
#define pyload_CONSTANTS_H

#include "pyload_types.h"

namespace Pyload {

class pyloadConstants {
 public:
  pyloadConstants();

};

extern const pyloadConstants g_pyload_constants;

} // namespace

#endif
