/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "pyload_constants.h"

namespace Pyload {

const pyloadConstants g_pyload_constants;

pyloadConstants::pyloadConstants() {
}

} // namespace

