/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pyload_constants.h"

namespace Pyload {

const pyloadConstants g_pyload_constants;

pyloadConstants::pyloadConstants() {
}

} // namespace

